spring:
  thymeleaf:
    prefix:
      classpath: /templates/
    check-template-location: true
    cache: false
    suffix: .html
    encoding: UTF-8
    mode: HTML5
    servlet:
      content-type: text/html
  datasource:
    url: jdbc:mysql://localhost:3306/springbootdb?serverTimezone=CTT
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    view:
      prefix: /templates/
      suffix: .html
